### ISSUE TITLE
Unable to install 1.1.0 on OSX 10.9.5

### ISSUE THREAD

**Issue by rtdean** [Yubico/yubikey-neo-manager#31]
Also tried 1.0.0, same issue.  When running the installer, it bails out and displays this failure message:

![screen shot 2015-01-20 at 1 17 13 pm](https://cloud.githubusercontent.com/assets/5319942/5826317/af10e99c-a0a6-11e4-98d0-3605890b23e1.png)

**Comment by dainnilsson** [comment]
It's likely that the installer is having problems while trying to patch your /usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist file. Perhaps the file is corrupted in some way.

What you can try doing is creating a backup of the file you have and replace it with a clean unmodified file, then try running the installer again. Here's a fresh copy of the file: https://gist.github.com/dainnilsson/0afa0f8786e06ca9f729

To save it, click on "raw", then save the file using your browser.

**Comment by rtdean** [comment]
Well, that allowed the Neo app to install.  I'm having issues when running the device in certain modes (OTP+CCID+U2F, for example), but I'll open a separate ticket on those.
