### ISSUE TITLE
Qt interface on ubuntu

### ISSUE THREAD

**Issue by jackwasey** [Yubico/yubikey-neo-manager#32]
I realise that you Qt lets you build cross platform, but this is the sole Qt application on my busy Ubuntu 14.04 LTS machine, and it looks very ugly with default settings for everything, and now I'm also dragging in a load of KDE, phonon dependencies.

**Comment by dainnilsson** [comment]
So, what's the actual issue here?

**Comment by jackwasey** [comment]
Hi. I think the issue is bringing in Qt dependencies in Ubuntu, which I highly expect you to disagree with, but since: Qt is not part of a regular Ubuntu installation, it carries a lot of dependencies, and looks ugly, I think most people would prefer a Gtk interface.

**Comment by dainnilsson** [comment]
This application is a QT app and will remain so, however you have a few options:

First off, you can use the command line tools accompanying the underlying libraries, which are all available from our PPA as well. These are pretty lightweight in dependencies.

If you're looking for a GTK version, you're out of luck, unless you write one yourself. Feel free to do so.

Lastly, I believe a lot of the QT dependencies can (and probably should) actually be removed (such as Phonon) as they are not used. I've created an issue to track this: Yubico/yubikey-neo-manager-dpkg#3.
