### ISSUE TITLE
Detect and report failure to change connection modes

### ISSUE THREAD

**Issue by doherty** [Yubico/yubikey-neo-manager#33]
If you have protected profiles, you can't change the connection modes. http://forum.yubico.com/viewtopic.php?p=6317#p6317

Currently, that's not detected and reported. The application tells the user to remove their yubikey, but when they reinsert it, they discover that the connection modes are unchanged.

Instead, the user should be warned, and told how to remove the protection so connection modes can be changed. Better yet, you should be able to change connection modes normally in this situation.

**Comment by dainnilsson** [comment]
This should definitely be detected by the tool and notified to the user. That should be pretty simple to implement, and a good first step.

Even better would be to allow the user to provide the access code(s) to un-set them, switch modes,then re-set them again, but this introduces a whole world of extra complexity and gotchas. Where the current mode has to be considered, if the YubiKey slot is updateable, etc. etc. I'm not sure this can be done in a satisfactory fashion.

**Comment by dainnilsson** [comment]
I'm pushing a fix to this that closes the issue. Due to a bug in one of the underlying libraries, libykneomgr, the tool still won't report failure to switch modes when CCID is enabled, unless you have the latest libykneomgr built from source.
