### ISSUE TITLE
NEO Manager on Mac OS X: Two UI fields need to be adjusted to accommodate field size

### ISSUE THREAD

**Issue by SueHeim** [Yubico/yubikey-neo-manager#35]
When viewing the NEO Manager on a Mac system, two fields show text that is cut off. It appears the fields just need to be enlarged slightly to accommodate the text without getting cut off. See attached screen shot.
![neo_manager_ui_issue_mac](https://cloud.githubusercontent.com/assets/12145100/7503196/2ba5b454-f3f6-11e4-9143-06285516dc4b.jpg)

**Comment by dainnilsson** [comment]
The screenshot shows you're running version 0.2.2. Please try the latest version (1.2.1) and see if you have the same issue there. If so, reopen this issue. I'm closing it for now.
