### ISSUE TITLE
Add linux installation instructions

### ISSUE THREAD

**Issue by tshanks** [Yubico/yubikey-neo-manager#38]
For the sake of Linux users who are not developers like us, please provide installation instructions and consider adding this package to an Ubuntu PPA.

**Comment by dainnilsson** [comment]
It's available in this PPA: https://launchpad.net/~yubico/+archive/ubuntu/stable

Clearer instructions will be added to the README momentarily!

**Comment by dainnilsson** [comment]
Nevermind, the instructions in the README are already quite clear. The link to the PPA is in the README in the _Installation_ section.
