### ISSUE TITLE
Why are you shipping user32.dll?

### ISSUE THREAD

**Issue by SteveSyfuhs** [Yubico/yubikey-neo-manager#45]
Compatibility insanity aside, I don't think that's a redistributable DLL.

Also looks like its in PIV Manager too. (probably others, but I don't have them installed).

![image](https://cloud.githubusercontent.com/assets/1210849/10529085/f07424a4-7368-11e5-923b-b2dde14a3eca.png)
![image](https://cloud.githubusercontent.com/assets/1210849/10529090/f6a2b836-7368-11e5-9ef0-aac229922008.png)

**Comment by dainnilsson** [comment]
Thanks for reporting this! This looks like the result of a bug in PyInstaller: https://github.com/pyinstaller/pyinstaller/issues/795
In short, it's not used and it shouldn't have been part of the installation. I'll be replacing the installer to not bundle it shortly. In the meantime you can safely delete the file yourself.

**Comment by dainnilsson** [comment]
The installers for this project (1.3.0) and for YubiKey PIV Manager have now been updated. Note that installing on top of an existing installation will not remove any files, so either delete the file manually to get rid of it, or do a complete uninstall of the application before running the updated installer.

**Comment by SteveSyfuhs** [comment]
Awesome!
