### ISSUE TITLE
Applets not available in U2F+CCID mode

### ISSUE THREAD

**Issue by adiroiban** [Yubico/yubikey-neo-manager#49]
I have also reported it here as I don't know why this is not working https://github.com/Yubico/libykneomgr/issues/27

--------

Even if CCID is enabled I can not list the applets when U2F is also enabled

Here are the screenshots from neoman for top+ccid and u2f+ccid

![u2f_ccid](https://cloud.githubusercontent.com/assets/204609/10998656/5151cc44-849f-11e5-8c72-956cf016a9ca.png)

I can used them when OTP is enabled

![otp_ccid](https://cloud.githubusercontent.com/assets/204609/10998655/51487a9a-849f-11e5-92b9-01104e32b288.png)

Thanks!

**Comment by dainnilsson** [comment]
See Yubico/libykneomgr#27.
