### ISSUE TITLE
Firmware version appears/disappears or not displayed at all when NEO is inserted

### ISSUE THREAD

**Issue by brendanhoar** [Yubico/yubikey-neo-manager#51]
On Windows 10/Threshold 2 using Neo Manager 1.4.0.

If I insert a Yubikey Edge (based on Yubikey 4 hardware), it'll show the Firmware Version directly under the Change name button (e.g. 4.1.8).

If I then insert a Yubikey Neo, it may or may not show the firmware version (e.g. 3.4.3) for a split second under the Change Name button before the Available apps subtree populates. If the firmware version did show up momentarily, then as soon as the Available apps subtree populates, the Firmware version field disappears. Subsequent inserts of the Neo do not show the firmware version.

Whether or not the firmware version momentarily appears at all seems dependent upon whether the USB port has seen a USB CCID supporting yubikey device before.

**Comment by dainnilsson** [comment]
Yes, this is unfortunately intended behavior. Reading the firmware on a NEO cannot be done over CCID in a satisfactory way, so we've chosen not to do so. Switching to OTP-only mode should allow you to see the firmware version.
