### ISSUE TITLE
Package fro Ubuntu 16.10 on PPA?

### ISSUE THREAD

**Issue by MatzFan** [Yubico/yubikey-neo-manager#58]
Hi

I'm migrating from my old Mac to Ubuntu (16.10) and need yubikey-neo-manager. I see you have maintain a PPA, but that so far you do not have a 16.10 (Yakkety) package. Have you plans to add one soon? If not I'll install it by cloning from this repo.

Many thanks

**Comment by dainnilsson** [comment]
Yakkety already contains the latest version, you shouldn't need our PPA. Just "apt-get install yubikey-neo-manager".
