### ISSUE TITLE
Installing Yubikey Neo Manager on Ubuntu/Linux isn't clear in the documentation

### ISSUE THREAD

**Issue by mefarazath** [Yubico/yubikey-neo-manager#61]
https://developers.yubico.com/yubikey-neo-manager/  doesn't have information to help users install the neo manager on Ubuntu.

After circling around docs and forums I got it working with the below steps

1. Add the custom PPA
```
sudo add-apt-repository ppa:yubico/stable
sudo apt-get update
```

2. Launch the Neo Manager
`neoman`

(The name neoman isn't intuitive either)

I tried this on Ubuntu 14.04

**Comment by pfoo** [comment]
There is also no release for Zesty/17.04 and Artful/17.10

**Comment by gene1wood** [comment]
And no release for Bionic/18.04

This is likely because this project is deprecated (94859366f054636acc13f47fa02f2fbd0134da41) in favor of Yubikey Manager

**Comment by dagheyman** [comment]
@gene1wood is correct, this project is no longer supported.
